version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.18-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "ember-quickstart/yarn.lock" }}

      - run:
          name: install nginx
          command: sudo apt install nginx
          when: always
      - run:
          name: service nginx start
          command: sudo service nginx start
          when: always
      - run:
          name: service nginx status
          command: service nginx status
          when: always

      - run:
          name: sudo apt-get install software-properties-common
          command: sudo apt-get install -y software-properties-common
          when: always
      - run:
          name: sudo apt-get update
          command: sudo apt-get update
          when: always

      - run:
          name: gpg --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
          command: gpg --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
          when: always
      - run:
          name: gpg --export --armor  4F4EA0AAE5267A6C | sudo apt-key add -
          command: gpg --export --armor  4F4EA0AAE5267A6C | sudo apt-key add -
          when: always
      - run:
          name: echo -e "deb http://ppa.launchpad.net/ondrej/php/ubuntu/  xenial main" | sudo tee /etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list
          command: echo -e "deb http://ppa.launchpad.net/ondrej/php/ubuntu/  xenial main" | sudo tee /etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list
          when: always
      - run:
          name: sudo apt-get update
          command: sudo apt-get update
          when: always
      - run:
          name: sudo apt-get install php7.2 php7.2-cli php7.2-common
          command: sudo apt-get install php7.2 php7.2-cli php7.2-common
          when: always
      - run:
          name: sudo apt-get install php7.2-curl php7.2-gd php7.2-json php7.2-mbstring php7.2-intl php7.2-mysql php7.2-xml php7.2-zip
          command: sudo apt-get install php7.2-curl php7.2-gd php7.2-json php7.2-mbstring php7.2-intl php7.2-mysql php7.2-xml php7.2-zip
          when: always
      - run:
          name: php -v
          command: php -v
          when: always

      - run:
          name: sudo chmod 777 /etc/hosts
          command: sudo chmod 777 /etc/hosts
          when: always
      - run:
          name: sudo echo '127.0.0.1   accounts.ucraft.local developers.ucraft.local' >> /etc/hosts
          command: sudo echo '127.0.0.1   accounts.ucraft.local developers.ucraft.local' >> /etc/hosts
          when: always
      - run:
          name: cat /etc/hosts
          command: cat /etc/hosts
          when: always

      - run:
          name: sudo mkdir -p /var/www/html/accounts
          command: sudo mkdir -p /var/www/html/accounts
          when: always
      - run:
          name: sudo mkdir -p /var/www/html/builder
          command: sudo mkdir -p /var/www/html/builder
          when: always



workflows:
  version: 2
  build-and-test:
    jobs:
      - build

