version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.18-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "ember-quickstart/yarn.lock" }}


      - run:
          name: sudo mkdir -p /var/www/html/accounts
          command: sudo mkdir -p /var/www/html/accounts
          when: always
      - run:
          name: sudo mkdir -p /var/www/html/builder
          command: sudo mkdir -p /var/www/html/builder
          when: always



workflows:
  version: 2
  build-and-test:
    jobs:
      - build

